DROP TRIGGER BaixaEstoqueConsumo
GO

CREATE TRIGGER BaixaEstoqueVenda
ON T_ItensMateriaPrima
after INSERT
AS

DECLARE @parCod_Produto VARCHAR(5)
DECLARE @parQtde_venda Integer

DECLARE ItensVendas CURSOR FOR ( SELECT COD_MATERIAPRIMA, QTDE_UTILIZADA FROM INSERTED )
BEGIN

   OPEN ItensVendas
   FETCH NEXT FROM ItensVendas INTO @parCod_Produto,@parQtde_Venda
   WHILE @@FETCH_STATUS = 0
   BEGIN
      UPDATE T_Produtos set Saldo = Saldo-@parQtde_Venda where Codigo=@parCod_Produto
      FETCH NEXT FROM ItensVendas INTO @parCod_Produto,@parQtde_Venda
   END 
   CLOSE ItensVendas
   DEALLOCATE ItensVendas

   SET NOCOUNT ON

   INSERT INTO T_MOVESTOQUE
               ( COD_EMP,COD_PRODUTO,DATA_CAD,DATA_MOV, E_S, OPERADOR, DOCUMENTO,
                 QTDE_BAIXA, ROTINA,SALDO_ANTERIOR, SALDO_POSTERIOR               ) 
   SELECT        '001',INSERTED.COD_MATERIAPRIMA,INSERTED.DATA_CAD,INSERTED.DATA_CAD,'S',
                 INSERTED.OPERADOR,INSERTED.SEQVENDA,INSERTED.QTDE_UTILIZADA,'CONSUMO MATERIA PRIMA ',(T_PRODUTOS.SALDO+INSERTED.QTDE_UTILIZADA), 
                 T_PRODUTOS.SALDO
   FROM INSERTED INNER JOIN T_PRODUTOS
   ON INSERTED.COD_MATERIAPRIMA = T_PRODUTOS.CODIGO

   SET NOCOUNT OFF
END


