SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


CREATE TRIGGER SaldosVendas
ON T_ItensVendas
AFTER INSERT
AS

BEGIN
   SET NOCOUNT ON
   INSERT INTO T_Saldos
               ( COD_EMP,COD_PRODUTO,DATA_CAD,DATA_MOV, E_S, OPERADOR,
                 QTDE,HISTORICO,PCO_CUSTO,PCO_VENDA,codigo,Tipo_Movimento ) 
   SELECT        '001',INSERTED.COD_PRODUTO,INSERTED.DATA_CAD,INSERTED.DATA_MOV,'S',
                 INSERTED.OPERADOR,INSERTED.QTDE_Venda,'VENDA  Nº',
                 T_PRODUTOS.PCO_COMPRA,INSERTED.PCO_VENDA,INSERTED.seqvenda,'VENDA DE MERCADORIA'   
   FROM INSERTED INNER JOIN T_PRODUTOS
   ON INSERTED.COD_PRODUTO = T_PRODUTOS.CODIGO and T_produtos.Tipo_Produto<>'1'

   SET NOCOUNT OFF
END




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

