set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go



create TRIGGER [SaldosAvarias]
ON [dbo].[T_ItensAvarias]
AFTER INSERT
AS

BEGIN
   SET NOCOUNT ON
   INSERT INTO T_Saldos
               ( COD_EMP,COD_PRODUTO,DATA_CAD,DATA_MOV, E_S, OPERADOR,
                 QTDE,HISTORICO,PCO_CUSTO,PCO_VENDA,codigo,Tipo_Movimento ) 
   SELECT        '001',INSERTED.COD_PRODUTO,INSERTED.DATA_CAD,INSERTED.DATA_MOV,'S',
                 INSERTED.OPERADOR,INSERTED.QTDE_avaria,'AVARIA  Nº',
                 T_PRODUTOS.PCO_COMPRA,INSERTED.PCO_VENDA,INSERTED.seqavaria,'MERCADORIA AVARIADA'   
   FROM INSERTED INNER JOIN T_PRODUTOS
   ON INSERTED.COD_PRODUTO = T_PRODUTOS.CODIGO and T_produtos.Tipo_Produto<>'1'

   SET NOCOUNT OFF
END
