SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


CREATE TRIGGER SaldosEntradas
ON T_ItensEntradas
AFTER INSERT
AS

BEGIN

   SET NOCOUNT ON
   INSERT INTO T_Saldos
               ( COD_EMP,COD_PRODUTO,DATA_CAD,DATA_MOV, E_S, OPERADOR,
                 QTDE,HISTORICO,PCO_CUSTO,PCO_VENDA,Codigo,Tipo_movimento ) 
   SELECT        '001',INSERTED.COD_PRODUTO,INSERTED.DATA_CAD,INSERTED.DATA_MOV,'E',
                 INSERTED.OPERADOR,INSERTED.QTDE_Entrada,'ENTRDADA Nº',
                 INSERTED.Pco_entrada,T_PRODUTOS.PCO_VENDA,INSERTED.SEQENTRADA,'ENTRADA DE MERCADORIA'   
   FROM INSERTED INNER JOIN T_PRODUTOS
   ON INSERTED.COD_PRODUTO = T_PRODUTOS.CODIGO and T_produtos.Tipo_Produto<>'1'

   SET NOCOUNT OFF
END




GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

