unit TestDaoRemessa;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Remessa, SqltimSt, Classes, DaoRemessa, SysUtils, DbClient, uClassConexao;

type
  // Test methods for class TDaoRemessa

  TestTDaoRemessa = class(TTestCase)
  strict private
    FDaoRemessa: TDaoRemessa;
    FConexao : TConexao;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSomarItemNaRemessa;
    procedure TestBuscarRemessaAberta;
    procedure TestRetornarRemessasAbertas;
    procedure TestTemRemessaAberta;
  end;

implementation

procedure TestTDaoRemessa.SetUp;
begin
  Fconexao := TConexao.Create();
  FDaoRemessa := TDaoRemessa.Create();
end;

procedure TestTDaoRemessa.TearDown;
begin
  FDaoRemessa.Free;
  FDaoRemessa := nil;
end;

procedure TestTDaoRemessa.TestSomarItemNaRemessa;
var
  operador: string;
  Quantidade: Integer;
  ProdutoId: Integer;
  SupervisorId: Integer;
begin
  // TODO: Setup method call parameters
  FDaoRemessa.SomarItemNaRemessa(SupervisorId, ProdutoId, Quantidade, operador);
  // TODO: Validate method results
end;

procedure TestTDaoRemessa.TestBuscarRemessaAberta;
var
  ReturnValue: TRemessa;
  SupervisorId: Integer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FDaoRemessa.BuscarRemessaAberta(SupervisorId);
  // TODO: Validate method results
end;

procedure TestTDaoRemessa.TestRetornarRemessasAbertas;
var
  ReturnValue: TClientDataSet;
begin
  ReturnValue := FDaoRemessa.RetornarRemessasAbertas;
  // TODO: Validate method results
end;

procedure TestTDaoRemessa.TestTemRemessaAberta;
var
  ReturnValue: Boolean;
  SupervisorId: Integer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FDaoRemessa.TemRemessaAberta(SupervisorId);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDaoRemessa.Suite);
end.

