
Create Table [T_PARAMETROS] (CHAVE VARCHAR (30), COD_EMP VARCHAR (3), CODIGO SMALLINT, DATA_ATU DATETIME, DATA_CAD DATETIME, DESCRICAO VARCHAR (255), ESTACAO VARCHAR (30), OPERADOR VARCHAR (20), VALOR VARCHAR (255))
